export type ExperienceLabGuide = {
  purpose: string;
  mechanics: string;
  customize: string;
  fallback: string;
  source: string;
  docs: string;
};

const guide = (source: string, docs: string, purpose: string, mechanics: string, customize: string, fallback: string): ExperienceLabGuide => ({ purpose, mechanics, customize, fallback, source, docs });

export const experienceLabGuides: Record<string, ExperienceLabGuide> = {
  "depth-camera-scene": guide("src/components/experience/depth-camera-scene.tsx", "docs/experience/depth-camera-scene.md", "Rezervat pentru reconstrucția separată 2.5D Advanced de la zero; preview-ul curent nu este direcția finală.", "PerspectiveCamera reală, plate-uri în două pass-uri WebGL și copy DOM între ele pentru ocluzie.", "Stack-ul 00–50, asset-urile înregistrate, dolly-ul, momentele de copy, crop-ul mobil și ritmul.", "Poster compozit dedicat, stack mobil și scenă semantică fără mișcare."),
  "layered-depth": guide("src/components/experience/layered-depth.tsx", "docs/experience/scroll-depth-scene.md", "2.5D Basic pentru un master integrat și o ocluzie simplă în jurul subiectului.", "Layere DOM cu timeline normalizat, transformări diferențiate și progres din scroll vertical.", "Master, matte exact, copy, ranges, scale, depth și lungimea secțiunii.", "Master static complet; fără parallax simulat dacă matte-ul lipsește."),
  "spatial-product-stage": guide("src/components/experience/spatial-product-stage.tsx", "docs/experience/spatial-product-stage.md", "Arată construcția sau exploded view-ul unui produs real.", "Three.js cu primitive, plate-uri alpha ori noduri GLB și driver hover/scroll/hybrid.", "Piese, transformări, delay, ancoră, cameră, material, control și copie.", "Produs complet și lizibil, fără piese fantomă în idle."),
  "liquid-glass": guide("src/components/experience/liquid-glass.tsx", "docs/experience/liquid-glass.md", "Suprafață și navigație clară care păstrează contextul scenei din spate.", "Backdrop filters, highlights adaptive, pointer light bounded și structură semantică.", "Tint, blur, saturație, transparență, radius, nav items și starea activă.", "Suprafață transparentă cu contrast verificat și motion redus."),
  "shader-field": guide("src/components/experience/shader-field.tsx", "docs/experience/shader-field.md", "Ambient GPU editabil pentru lumină, energie sau materialitate.", "Shader full-screen cu patru moduri, pointer damped, DPR cap și pauză offscreen.", "Mod, trei culori, intensitate, viteză, pointer strength și copy.", "Gradient static brand-uit cu aceeași lizibilitate."),
  "media-portal": guide("src/components/experience/media-portal.tsx", "docs/experience/media-portal.md", "Deschide o fereastră media până devine o lume full viewport.", "Clip/radius continuu pe un timeline scroll și conținut React în apertură.", "Formă, dimensiune inițială, media, backdrop, scroll length și overlay.", "Media completă sau poster static; fără apertură incompletă."),
  "spatial-gallery": guide("src/components/experience/spatial-gallery.tsx", "docs/experience/spatial-gallery.md", "Galerie cinematică în care camera traversează cadre separate.", "Plane-uri Three.js, cameră scroll-driven, vizibilitate deterministă și captions DOM.", "Imagini, distanțe, focus, titluri, crop și viteza camerei.", "Rail nativ cu snap pe touch și reduced motion."),
  "mesh-transition": guide("src/components/experience/mesh-transition.tsx", "docs/experience/mesh-transition.md", "Face o singură tranziție materială între două imagini înregistrate.", "Mesh subdivizat și displacement shader cu endpoint-uri exacte.", "Surse, mode, amplitudine, seam, timing, overscan și copy.", "Una dintre imaginile complete; fără margini negre sau stare intermediară."),
  "horizontal-story-rail": guide("src/components/experience/horizontal-story-rail.tsx", "docs/experience/horizontal-story-rail.md", "Transformă scroll-ul vertical nativ într-o poveste orizontală măsurată.", "Sticky stage, track dimensionat din DOM și progres reversibil fără scroll trap.", "Carduri de orice lățime, gap, padding, scroll length și layout intern.", "Rail orizontal nativ cu snap unde sticky motion nu este potrivit."),
  "horizontal-track": guide("src/components/experience/horizontal-track.tsx", "docs/experience/horizontal-track.md", "Infrastructură orizontală controlată de un timeline sau UI părinte.", "MotionValue extern mapat pe distanța reală a track-ului.", "Controller, dimensiuni mixte, controale, easing și conținut.", "Listă/rail controlabil fără automatizare de scroll."),
  "sticky-story": guide("src/components/experience/sticky-story.tsx", "docs/experience/sticky-story.md", "Leagă mai multe capitole de un vizual persistent care își schimbă starea.", "CSS sticky, praguri observate și crossfade determinist al vizualurilor.", "Capitole, poziția imaginii, alternarea stânga/dreapta, surse și copy.", "Capitole verticale cu vizualul fiecăruia în flow."),
  "image-sequence-scrub": guide("src/components/experience/image-sequence-scrub.tsx", "docs/experience/image-sequence-scrub.md", "Leagă scroll-ul de cadre reale pentru rotații sau transformări frame-perfect.", "Canvas 2D, preloading prioritizat, frame index determinist și poster.", "Cadre, poster, frame count, scroll length, fit și overlay.", "Poster reprezentativ, cu bugetul de cadre documentat."),
  "mask-reveal": guide("src/components/experience/mask-reveal.tsx", "docs/experience/mask-reveal.md", "Dezvăluie o stare sau informație în aceeași compoziție.", "Clip-path/mask cu scrub sau commit și progres reversibil corect.", "Direcție, formă, surse, range, playback și overlay.", "Starea finală completă; required copy nu depinde de reveal."),
  "kinetic-type": guide("src/components/experience/kinetic-type.tsx", "docs/experience/kinetic-type.md", "Folosește tipografia semantică drept principalul material de mișcare.", "Segmente DOM cu ranges, transforms 2D/3D și progres din scroll.", "Cuvinte, ierarhie, ranges, easing, font, culoare și spațiere.", "Aceeași propoziție într-o compoziție statică lizibilă."),
  "cursor-ambient": guide("src/components/experience/cursor-ambient.tsx", "docs/experience/cursor-lens.md", "Lasă pointerul să descopere o a doua stare fără a ascunde cursorul nativ.", "Mask radial local, pointer smoothing și versiune statică pe touch.", "Lens size, label, sursele base/reveal, contrast și conținut.", "Starea de bază completă; pe touch poate exista un CTA explicit."),
  "before-after": guide("src/components/experience/before-after.tsx", "docs/experience/before-after.md", "Compară exact două imagini înregistrate.", "Range input nativ, clip procentual și handle semantic.", "Surse, labels, orientare, valoare inițială și icon handle.", "Ambele imagini și explicația diferenței rămân accesibile."),
  "expanding-media": guide("src/components/experience/expanding-media.tsx", "docs/experience/expanding-media.md", "Ridică un cadru editorial până devine media full viewport.", "Dimensiuni interpolate, sticky timeline și playback scrub/commit.", "Media, frame, radius, margins, copy, range și durată.", "Media finală completă într-un bloc normal."),
  "cursor-magnetic": guide("src/components/experience/cursor-magnetic.tsx", "docs/experience/cursor-magnetic.md", "Adaugă răspuns local de proximitate pe câteva ținte importante.", "RAF damped per target, travel și tilt bounded; cursorul nativ rămâne.", "Rază, strength, travel, tilt și ierarhia țintelor.", "Grid static identic pe touch, keyboard și reduced motion."),
  "depth-gallery": guide("src/components/experience/depth-gallery.tsx", "docs/experience/depth-gallery.md", "Construiește o succesiune focală de cadre suprapuse.", "Stack DOM determinist: cadrul activ se ridică, următorul rămâne dedesubt.", "Cadre, offset, durată, captions, radius și fundal.", "Rail nativ swipe, fără schimbări arbitrare de z-index."),
  "refractive-glass": guide("src/components/experience/refractive-glass.tsx", "docs/experience/refractive-glass.md", "Adaugă materialitate printr-un singur lens care refractă scena reală.", "Shader image-aware cu displacement, magnification, chromatic edge și pointer damped.", "Sursa, crop mobil, shape, size, aspect, refraction, aberration și copy.", "Poster + lens CSS static; WebGL are DPR cap, offscreen pause și context fallback."),
  "product-orbit": guide("src/components/experience/product-orbit.tsx", "docs/experience/product-orbit.md", "Permite inspecția unei forme de produs și explică detalii reale.", "Three.js/GLTFLoader, drag + arrows, materiale fizice și hotspots proiectate din model space.", "GLB, cameră, scară, material, auto-rotate, hotspots și panel content.", "Poster complet; ordinary wheel rămâne scroll de pagină."),
  "particle-assembly": guide("src/components/experience/particle-assembly.tsx", "docs/experience/particle-assembly.md", "Transformă semnalul sau materia într-un obiect recognoscibil.", "Mask raster eșantionat în point cloud; al doilea asset poate furniza culorile target-ului.", "Mask, color source, sampling, point count/size, scatter, color mix și driver.", "Imagine completă a obiectului; niciodată un stage gol fără WebGL."),
  "typography-depth-tunnel": guide("src/components/experience/typography-depth-tunnel.tsx", "docs/experience/typography-depth-tunnel.md", "Creează o secvență de manifesto în care distanța devine ierarhie.", "CSS 3D semantic, sloturi exclusive și spring peste progresul scroll.", "Phrases, align, depth, perspective, smoothing, scroll length și styles.", "Secvență verticală normală pe narrow/reduced motion."),
  "spatial-canvas": guide("src/components/experience/spatial-canvas.tsx", "docs/experience/spatial-canvas.md", "Explorează arhive sau relații non-liniare pe un plan.", "Pan/zoom DOM cu pointer, tastatură și controls; wheel-ul paginii nu este capturat.", "Coordonate, world size, initial view, zoom bounds, grid și fiecare item.", "Rail snap nativ pe mobil și reduced motion."),
  "volumetric-light-stage": guide("src/components/experience/volumetric-light-stage.tsx", "docs/experience/volumetric-light-stage.md", "Art-direcționează un cadru existent prin lumină și atmosferă.", "Shader image-backed cu trei emitters, procedural breakup, haze și pointer light.", "Imagine, emitter x/width/angle/color/intensity, density, haze și speed.", "Imaginea clean cu grading static și contrast echivalent."),
  "slice-recompose": guide("src/components/experience/slice-recompose.tsx", "docs/experience/slice-recompose.md", "Comunică reconstrucție sau modularitate printr-o singură sursă.", "Layere full-frame clipate cu overlap subpixel și timeline per slice.", "Sursă, axă, slice count, scatter, rotation, stagger și driver.", "Sursa complet asamblată, fără seam, gap sau crop diferit."),
  "film-strip-3d": guide("src/components/experience/film-strip-3d.tsx", "docs/experience/film-strip-3d.md", "Păstrează contextul mai multor cadre în timp ce unul intră în focus.", "Carduri React pe o curbă CSS 3D, cu x/z/rotate/opacity dintr-un progres comun.", "Items, spacing, curve, perspective, frame size, captions și ritm.", "Rail snap nativ pe mobil și reduced motion."),
  "elastic-image-grid": guide("src/components/experience/elastic-image-grid.tsx", "docs/experience/elastic-image-grid.md", "Face un grid curatorial să răspundă la proximitate fără să-i rupă structura.", "Câmp RAF per tile cu damped travel, scale și tilt; zero layout shift.", "Items, min width, radius, travel, scale, tilt și smoothing.", "Grid static complet pe touch, keyboard și reduced motion."),
  "fluid-surface": guide("src/components/experience/fluid-surface.tsx", "docs/experience/fluid-surface.md", "Sugerează apă sau memorie materială prin impulsuri discrete în imagine.", "Shader image-aware cu maximum cinci unde care se disipă, DPR cap și pauză offscreen.", "Sursă, strength, radius, decay, chromatic edge și copy.", "Imagine statică completă pe touch/reduced motion; cursorul nativ rămâne."),
  "scene-handoff": guide("src/components/experience/scene-handoff.tsx", "docs/experience/scene-handoff.md", "Leagă două scene React complete într-un singur moment narativ.", "Scale, blur, opacity și clip geometry pe un timeline reversibil.", "Scene endpoints, variant depth/shutter/iris, scroll length, overlay și fallback.", "Cele două scene în flow normal sau fallback explicit."),
};
