export type ExperienceLabGuide = {
  purpose: string;
  mechanics: string;
  customize: string;
  fallback: string;
  source: string;
  docs: string;
};

const guide = (source: string, docs: string, purpose: string, mechanics: string, customize: string, fallback: string): ExperienceLabGuide => ({ purpose, mechanics, customize, fallback, source, docs });

export const experienceLabGuides: Record<string, ExperienceLabGuide> = {
  "layered-depth": guide("src/components/experience/layered-depth.tsx", "docs/experience/scroll-depth-scene.md", "2.5D Basic pentru un master integrat și o ocluzie simplă în jurul subiectului.", "Layere DOM cu timeline normalizat, transformări diferențiate și progres din scroll vertical.", "Master, matte exact, copy, ranges, scale, depth și lungimea secțiunii.", "Master static complet; fără parallax simulat dacă matte-ul lipsește."),
  "spatial-product-stage": guide("src/components/experience/spatial-product-stage.tsx", "docs/experience/spatial-product-stage.md", "Arată construcția sau exploded view-ul unui produs real.", "Three.js cu primitive, plate-uri alpha ori noduri GLB și driver hover/scroll/hybrid.", "Piese, transformări, delay, ancoră, cameră, material, control și copie.", "Produs complet și lizibil, fără piese fantomă în idle."),
  "liquid-glass": guide("src/components/experience/liquid-glass.tsx", "docs/experience/liquid-glass.md", "Suprafață și navigație clară care păstrează contextul scenei din spate.", "Backdrop filters, highlights adaptive, pointer light bounded și structură semantică.", "Tint, blur, saturație, transparență, radius, nav items și starea activă.", "Suprafață transparentă cu contrast verificat și motion redus."),
  "shader-field": guide("src/components/experience/shader-field.tsx", "docs/experience/shader-field.md", "Ambient GPU editabil pentru lumină, energie sau materialitate.", "Shader full-screen cu patru moduri, pointer damped, DPR cap și pauză offscreen.", "Mod, trei culori, intensitate, viteză, pointer strength și copy.", "Gradient static brand-uit cu aceeași lizibilitate."),
  "media-portal": guide("src/components/experience/media-portal.tsx", "docs/experience/media-portal.md", "Deschide o fereastră media până devine o lume full viewport.", "Clip/radius continuu pe un timeline scroll și conținut React în apertură.", "Formă, dimensiune inițială, media, backdrop, scroll length și overlay.", "Media completă sau poster static; fără apertură incompletă."),
  "spatial-gallery": guide("src/components/experience/spatial-gallery.tsx", "docs/experience/spatial-gallery.md", "Galerie cinematică în care camera traversează cadre separate.", "Plane-uri Three.js, cameră scroll-driven, vizibilitate deterministă și captions DOM.", "Imagini, distanțe, focus, titluri, crop și viteza camerei.", "Rail nativ cu snap pe touch și reduced motion."),
  "mesh-transition": guide("src/components/experience/mesh-transition.tsx", "docs/experience/mesh-transition.md", "Face o singură tranziție materială între două imagini înregistrate.", "Mesh subdivizat și displacement shader cu endpoint-uri exacte.", "Surse, mode, amplitudine, seam, timing, overscan și copy.", "Una dintre imaginile complete; fără margini negre sau stare intermediară."),
  "horizontal-story-rail": guide("src/components/experience/horizontal-story-rail.tsx", "docs/experience/horizontal-story-rail.md", "Transformă scroll-ul vertical nativ într-o poveste orizontală măsurată.", "Sticky stage, track dimensionat din DOM și progres reversibil fără scroll trap.", "Carduri de orice lățime, gap, padding, scroll length și layout intern.", "Rail orizontal nativ cu snap unde sticky motion nu este potrivit."),
  "horizontal-track": guide("src/components/experience/horizontal-track.tsx", "docs/experience/horizontal-track.md", "Infrastructură orizontală controlată de un timeline sau UI părinte.", "MotionValue extern mapat pe distanța reală a track-ului.", "Controller, dimensiuni mixte, controale, easing și conținut.", "Listă/rail controlabil fără automatizare de scroll."),
  "sticky-story": guide("src/components/experience/sticky-story.tsx", "docs/experience/sticky-story.md", "Leagă mai multe capitole de un vizual persistent care își schimbă starea.", "CSS sticky, praguri observate și crossfade determinist al vizualurilor.", "Capitole, poziția imaginii, alternarea stânga/dreapta, surse și copy.", "Capitole verticale cu vizualul fiecăruia în flow."),
  "image-sequence-scrub": guide("src/components/experience/image-sequence-scrub.tsx", "docs/experience/image-sequence-scrub.md", "Leagă scroll-ul de cadre reale pentru rotații sau transformări frame-perfect.", "Canvas 2D, preloading prioritizat, frame index determinist și poster.", "Cadre, poster, frame count, scroll length, fit și overlay.", "Poster reprezentativ, cu bugetul de cadre documentat."),
  "mask-reveal": guide("src/components/experience/mask-reveal.tsx", "docs/experience/mask-reveal.md", "Dezvăluie o stare sau informație în aceeași compoziție.", "Clip-path/mask cu scrub sau commit și progres reversibil corect.", "Direcție, formă, surse, range, playback și overlay.", "Starea finală completă; required copy nu depinde de reveal."),
  "kinetic-type": guide("src/components/experience/kinetic-type.tsx", "docs/experience/kinetic-type.md", "Folosește tipografia semantică drept principalul material de mișcare.", "Segmente DOM cu ranges, transforms 2D/3D și progres din scroll.", "Cuvinte, ierarhie, ranges, easing, font, culoare și spațiere.", "Aceeași propoziție într-o compoziție statică lizibilă."),
  "cursor-ambient": guide("src/components/experience/cursor-ambient.tsx", "docs/experience/cursor-lens.md", "Lasă pointerul să descopere o a doua stare fără a ascunde cursorul nativ.", "Mask radial local, pointer smoothing și versiune statică pe touch.", "Lens size, label, sursele base/reveal, contrast și conținut.", "Starea de bază completă; pe touch poate exista un CTA explicit."),
  "before-after": guide("src/components/experience/before-after.tsx", "docs/experience/before-after.md", "Compară exact două imagini înregistrate.", "Range input nativ, clip procentual și handle semantic.", "Surse, labels, orientare, valoare inițială și icon handle.", "Ambele imagini și explicația diferenței rămân accesibile."),
  "expanding-media": guide("src/components/experience/expanding-media.tsx", "docs/experience/expanding-media.md", "Ridică un cadru editorial până devine media full viewport.", "Dimensiuni interpolate, sticky timeline și playback scrub/commit.", "Media, frame, radius, margins, copy, range și durată.", "Media finală completă într-un bloc normal."),
  "cursor-magnetic": guide("src/components/experience/cursor-magnetic.tsx", "docs/experience/cursor-magnetic.md", "Adaugă răspuns local de proximitate pe câteva ținte importante.", "RAF damped per target, travel și tilt bounded; cursorul nativ rămâne.", "Rază, strength, travel, tilt și ierarhia țintelor.", "Grid static identic pe touch, keyboard și reduced motion."),
  "depth-gallery": guide("src/components/experience/depth-gallery.tsx", "docs/experience/depth-gallery.md", "Construiește o succesiune focală de cadre suprapuse.", "Stack DOM determinist: cadrul activ se ridică, următorul rămâne dedesubt.", "Cadre, offset, durată, captions, radius și fundal.", "Rail nativ swipe, fără schimbări arbitrare de z-index."),
  "refractive-glass": guide("src/components/experience/refractive-glass.tsx", "docs/experience/refractive-glass.md", "Adaugă materialitate printr-un singur lens care refractă scena reală.", "Shader image-aware cu displacement, magnification, chromatic edge și pointer damped.", "Sursa, crop mobil, shape, size, aspect, refraction, aberration și copy.", "Poster + lens CSS static; WebGL are DPR cap, offscreen pause și context fallback."),
  "product-orbit": guide("src/components/experience/product-orbit.tsx", "docs/experience/product-orbit.md", "Permite inspecția unei forme de produs și explică detalii reale.", "Three.js/GLTFLoader, drag + arrows, materiale fizice și hotspots proiectate din model space.", "GLB, cameră, scară, material, auto-rotate, hotspots și panel content.", "Poster complet; ordinary wheel rămâne scroll de pagină."),
  "particle-assembly": guide("src/components/experience/particle-assembly.tsx", "docs/experience/particle-assembly.md", "Transformă semnalul sau materia într-un obiect recognoscibil.", "Mask raster eșantionat în point cloud; al doilea asset poate furniza culorile target-ului.", "Mask, color source, sampling, point count/size, scatter, color mix și driver.", "Imagine completă a obiectului; niciodată un stage gol fără WebGL."),
  "typography-depth-tunnel": guide("src/components/experience/typography-depth-tunnel.tsx", "docs/experience/typography-depth-tunnel.md", "Creează o secvență de manifesto în care distanța devine ierarhie.", "CSS 3D semantic, sloturi exclusive și spring peste progresul scroll.", "Phrases, align, depth, perspective, smoothing, scroll length și styles.", "Secvență verticală normală pe narrow/reduced motion."),
  "spatial-canvas": guide("src/components/experience/spatial-canvas.tsx", "docs/experience/spatial-canvas.md", "Explorează arhive sau relații non-liniare pe un plan.", "Pan/zoom DOM cu pointer, tastatură și controls; wheel-ul paginii nu este capturat.", "Coordonate, world size, initial view, zoom bounds, grid și fiecare item.", "Rail snap nativ pe mobil și reduced motion."),
  "volumetric-light-stage": guide("src/components/experience/volumetric-light-stage.tsx", "docs/experience/volumetric-light-stage.md", "Art-direcționează un cadru existent prin lumină și atmosferă.", "Shader image-backed cu trei emitters, procedural breakup, haze și pointer light.", "Imagine, emitter x/width/angle/color/intensity, density, haze și speed.", "Imaginea clean cu grading static și contrast echivalent."),
  "slice-recompose": guide("src/components/experience/slice-recompose.tsx", "docs/experience/slice-recompose.md", "Comunică reconstrucție sau modularitate printr-o singură sursă.", "Layere full-frame clipate cu overlap subpixel și timeline per slice.", "Sursă, axă, slice count, scatter, rotation, stagger și driver.", "Sursa complet asamblată, fără seam, gap sau crop diferit."),
  "film-strip-3d": guide("src/components/experience/film-strip-3d.tsx", "docs/experience/film-strip-3d.md", "Păstrează contextul mai multor cadre în timp ce unul intră în focus.", "Carduri React pe o curbă CSS 3D, cu x/z/rotate/opacity dintr-un progres comun.", "Items, spacing, curve, perspective, frame size, captions și ritm.", "Rail snap nativ pe mobil și reduced motion."),
  "elastic-image-grid": guide("src/components/experience/elastic-image-grid.tsx", "docs/experience/elastic-image-grid.md", "Face un grid curatorial să răspundă la proximitate fără să-i rupă structura.", "Câmp RAF per tile cu damped travel, scale și tilt; zero layout shift.", "Items, min width, radius, travel, scale, tilt și smoothing.", "Grid static complet pe touch, keyboard și reduced motion."),
  "fluid-surface": guide("src/components/experience/fluid-surface.tsx", "docs/experience/fluid-surface.md", "Sugerează apă sau memorie materială prin impulsuri discrete în imagine.", "Shader image-aware cu maximum cinci unde care se disipă, DPR cap și pauză offscreen.", "Sursă, strength, radius, decay, chromatic edge și copy.", "Imagine statică completă pe touch/reduced motion; cursorul nativ rămâne."),
  "scene-handoff": guide("src/components/experience/scene-handoff.tsx", "docs/experience/scene-handoff.md", "Leagă două scene React complete într-un singur moment narativ.", "Scale, blur, opacity și clip geometry pe un timeline reversibil.", "Scene endpoints, variant depth/shutter/iris, scroll length, overlay și fallback.", "Cele două scene în flow normal sau fallback explicit."),
  "shared-element-zoom": guide("src/components/experience/shared-element-zoom.tsx", "docs/experience/shared-element-zoom.md", "Transformă continuu un card din grid în vederea lui de detaliu.", "layoutId partajat cu morph FLIP, dialog semantic, focus management și scroll lock.", "Items, renderThumb/renderDetail, grid layout, overlay și close label.", "Fade simplu pe reduced motion; semantica de dialog rămâne identică."),
  "draw-on-scroll": guide("src/components/experience/draw-on-scroll.tsx", "docs/experience/draw-on-scroll.md", "Desenează formele stroked ale unui SVG pe măsură ce secțiunea traversează viewportul.", "stroke-dasharray/offset per formă, stagger configurabil și progres pinned sau de viewport.", "SVG-ul propriu, stagger, pin, scroll length, stroke styling și progresul extern.", "Desenul complet, imediat, pe reduced motion."),
  "marquee-velocity": guide("src/components/experience/marquee-velocity.tsx", "docs/experience/marquee-velocity.md", "Bandă infinită al cărei ritm reacționează la viteza scroll-ului.", "Măsurare + duplicare seamless, rAF cu damped velocity și pauză offscreen.", "Conținut, speed, velocity influence, direcție, gap și pause on hover.", "Strip static natively scrollabil pe reduced motion."),
  "variable-font-axis": guide("src/components/experience/variable-font-axis.tsx", "docs/experience/variable-font-axis.md", "Face din axele fontului variabil însăși mișcarea textului.", "font-variation-settings per caracter (pointer) sau per element (scroll), cu măsurători cache-uite.", "Text, axe from/to, mode, radius, smoothing și tipografia proprie.", "Text static la valorile de bază pe touch și reduced motion."),
  "image-trail": guide("src/components/experience/image-trail.tsx", "docs/experience/image-trail.md", "Lasă cursorul să împrăștie un trail decorativ de imagini în urma lui.", "Pool fix de carduri animate WAAPI, spawn la prag de distanță și reciclare fără alocări.", "Imagini, size, threshold, life, jitter și conținutul real din children.", "Doar conținutul (plus fallback static) pe touch și reduced motion."),
  "route-transition": guide("src/components/experience/route-transition.tsx", "docs/experience/route-transition.md", "Continuitate între rute și schimbări mari de stare prin View Transitions API.", "startViewTransition cu fallback, link/router wrappers, shared element names și theme wipe circular.", "Numele elementelor partajate, originea wipe-ului, durata și CSS-ul de override.", "Navigație instant, fără erori, pe browsere fără suport sau reduced motion."),
  "distortion-carousel": guide("src/components/experience/distortion-carousel.tsx", "docs/experience/distortion-carousel.md", "Galerie GPU în care drag-ul însuși este experiența, nu doar navigarea.", "Ofset continuu cu momentum și snap; viteza îndoaie imaginea, mută spectrul și trage cadrul spre cameră.", "Imagini, distortion, smoothing, drag sensitivity, captions, dots și labels.", "Rail nativ cu snap pe reduced motion sau fără WebGL; alt-urile rămân reale."),
  "portal-crossing": guide("src/components/experience/portal-crossing.tsx", "docs/experience/portal-crossing.md", "Fotografia originală umple ecranul; la scroll un portal 3D cu contur neregulat sosește din adâncul scenei și camera trece prin el în altă lume.", "Doar scroll, fără influență de cursor: nașterea e un morph din chiar pixelii fotografiei — o pată din imagine se îndoaie (pucker + vârtej), iar TOT portalul e camuflat în acei pixeli: fundalul, vălul aperturii și tubul marginii eșantionează aceeași fotografie deformată, continuu pixel-cu-pixel; dezvăluirea e condusă de distanța reală în timp ce portalul vine fizic din spate (fără scalare, ease-in-out): târziu și gradual, apertura se dizolvă spre destinație și în același timp marginea își face morph din materia fotografiei în tubul cu două lumi, deci nimic nu poate apărea brusc; rim-ul e un tub 3D viu pe un contur neregulat care ondulează în adâncime și respiră cu o undă lentă, texturat 50/50 pe creastă: interiorul cu lumea destinație, exteriorul cu lumea curentă — iar materia e liquid glass pe loc (pixelii ondulează refractat fără să circule pe cerc, meniscul dintre lumi tremură, un sheen respiră pe circumferință); apertura e stencil real, bloom la traversare, apoi arrival DOM preia cadrul. Reversibil complet.", "Origin/destination (src + alt), rimColors (accente halo/glow), irregularity, scroll length, overlay-ul cu progres și conținutul arrival.", "Imaginea destinației cu arrival vizibil static pe reduced motion sau fără WebGL."),
  "physics-playground": guide("src/components/experience/physics-playground.tsx", "docs/experience/physics-playground.md", "Badge-urile cad, se ciocnesc și pot fi aruncate — un teren de joacă fizic.", "Motor propriu de cercuri: integrare semi-implicită, coliziuni cu impuls, drag cinematic și sleep la repaus.", "Items, gravitate, restituție, stagger, dimensiunea scenei și stilul badge-urilor.", "Aranjament static flex-wrap pe reduced motion; aranjarea rămâne decorativă."),
  "holo-card": guide("src/components/experience/holo-card.tsx", "docs/experience/holo-card.md", "Tratament de carte de colecție: tilt 3D, foiță holografică și glare.", "Damped tilt spre pointer cu buclă care adoarme; foil color-dodge și glare radial conduse din CSS.", "maxTilt, foil, glare, stops, mască de foil, scale, radius și conținutul cardului.", "Card complet static pe touch și reduced motion; semantica stă în children."),
  "reveal-stagger": guide("src/components/experience/reveal-stagger.tsx", "docs/experience/reveal-stagger.md", "Coregrafia de intrare de zi cu zi: elemente care apar eșalonat când grupul intră în viewport.", "IntersectionObserver pe grup, CSS transitions per item cu delay din ordinea de randare; RevealText face split mascat pe cuvinte/caractere.", "Varianta, staggerMs, durata, distanța, once, delay-uri per item și tipografia din RevealText.", "SSR și reduced motion redau starea finală; conținutul nu depinde de JS."),
  "count-up": guide("src/components/experience/count-up.tsx", "docs/experience/count-up.md", "Statistici care numără spre valoarea reală la intrarea în viewport.", "rAF cu ease-out-expo, Intl.NumberFormat și layout rezervat de o copie invizibilă a valorii finale.", "value, from, durata, delay-ul de stagger, locale/formatOptions, prefix/sufix și easing-ul.", "Valoarea finală instant pe reduced motion și fără JS; aria citește doar rezultatul."),
  "hover-preview-list": guide("src/components/experience/hover-preview-list.tsx", "docs/experience/hover-preview-list.md", "Index editorial în care hoverul pe un rând invocă un panou media plutitor.", "Panou pointer-follow cu damping, tilt din viteză și crossfade determinist între preview-uri; focusul din tastatură îl ancorează lângă rând.", "Items (row + preview), lățimea/aspectul panoului, smoothing, tilt, stilurile rândurilor și fallback-ul inline.", "Pe touch și reduced motion panoul dispare, iar preview-urile pot intra inline în rânduri."),
  "text-scramble": guide("src/components/experience/text-scramble.tsx", "docs/experience/text-scramble.md", "Decodare de tip terminal pentru copy scurt tehnic.", "Sloturile se blochează stânga → dreapta cu jitter; restul licăresc prin charset într-un singur rAF.", "Text/phrases, trigger (visible/hover/load), durata, holdMs, charset-ul cu diacritice și stilul glifelor criptate.", "Text static pe reduced motion; ciclarea frazelor devine swap instant."),
  "spotlight-grid": guide("src/components/experience/spotlight-grid.tsx", "docs/experience/spotlight-grid.md", "Carduri bento iluminate de cursor, cu inel de bordură și glow interior.", "Un singur pointer field scrie CSS variables per card; inelul folosește mask-composite ca să moștenească border-radius.", "Radius, culoarea per grup/card, fillOpacity, borderWidth și conținutul cardurilor.", "Pe touch și reduced motion cardurile rămân statice cu bordurile lor proprii."),
  "scroll-stack": guide("src/components/experience/scroll-stack.tsx", "docs/experience/scroll-stack.md", "Carduri de proces care se fixează și se acoperă progresiv la scroll.", "Sticky per card cu peek incremental; acoperirea e măsurată live și mapată pe scale și dim, complet reversibil.", "topOffset, peek, gap, scaleStep, dim și cardurile ca children de orice înălțime.", "Listă verticală simplă pe reduced motion, cu aceeași ordine și conținut."),
  "knockout-text": guide("src/components/experience/knockout-text.tsx", "docs/experience/knockout-text.md", "Traversare tipografică fără aperturi artificiale: textul solid devine decupaj, apoi camera intră prin suprafața transparentă a unei litere centrale.", "Secțiune pinned: cuvântul apare complet, aceleași forme devin ferestre transparente către fotografie, apoi punctul ales din glyph este centrat progresiv în cameră în timp ce fotografia continuă un push-in real. Câmpul negru rămâne opac și nu există cerc radial sau derivă laterală.", "Textul, sursa + variantele responsive, scrollScreens, maxScale, imageMaxScale, litera centrală, passageX/passageY plasate în forma ei, overlay-ul și tipografia grea.", "Cuvânt static umplut cu fotografia, pe câmp opac și fără pin pe reduced motion."),
  "intro-loader": guide("src/components/experience/intro-loader.tsx", "docs/experience/intro-loader.md", "Coregrafie de intrare o dată pe sesiune sau loading screen controlat pentru orice încărcare reală.", "Counter legat de document load (eased spre 90%, cap dur) sau de `progress` extern; `active` ține cortina până eliberezi; exit cu cubic-bezier și scroll lock strict.", "minDurationMs, cuvintele, storageKey, active/progress pentru rute, galerii ori scene 3D, direcția de exit și brand mark-ul.", "Vizitatorii repetați și reduced motion sar complet peste; onComplete se apelează oricum."),
  "ambient-particles": guide("src/components/experience/ambient-particles.tsx", "docs/experience/ambient-particles.md", "Strat decorativ de atmosferă: dust, snow, embers sau fireflies pe canvas.", "Sprite-uri glow prerandate pe trei benzi de adâncime, edge fade spre marginile secțiunii, count scalat de arie, DPR cap, pauză offscreen și reproiectare la resize.", "Preset, culori, densitate, dimensiuni, viteză, edgeFade, blend și pointerInfluence.", "Nu randează nimic pe reduced motion; secțiunea trebuie să comunice identic fără strat."),
  "split-flap": guide("src/components/experience/split-flap.tsx", "docs/experience/split-flap.md", "Panou split-flap de aeroport pentru headline-uri și statusuri.", "Fiecare flip e derivat din timestamps (o rulare = startedAt + trasee pe roată), deci remount-urile nu pot bloca panoul; stagger pe coloane, tile-uri cu balamale și shrink-to-fit.", "Charset-ul (cu diacritice), stepMs, staggerMs, maxSteps, padTo, fit și tipografia mono.", "Text static simplu pe reduced motion; stringul complet rămâne numele accesibil."),
  "focus-transfer-rail": guide("src/components/experience/focus-transfer-rail.tsx", "docs/experience/focus-transfer-rail.md", "Mută prioritatea vizuală între două până la cinci cadre care trebuie comparate în același rând.", "Un progres scroll sau controlat interpolează flex-grow între panouri, păstrând ordinea și inversarea exactă la reverse scroll.", "Panourile React, activeRatio, idleRatio, pacing-ul per pas, crop-ul, track-ul și captions.", "Grid semantic static pe mobil, tabletă, coarse pointer și reduced motion, cu tot conținutul vizibil."),
  "spatial-fold": guide("src/components/experience/spatial-fold.tsx", "docs/experience/spatial-fold.md", "Transformă o succesiune scurtă de capitole React într-o arhitectură editorială care se pliază.", "Suprafețe DOM în CSS 3D, fiecare cu hinge declarat, perspectivă, umbră direcțională și progres scroll complet reversibil.", "Capitolele, ordinea hinge-urilor, perspective, maxFold, depth, shadowStrength, pacing și compoziția fiecărei suprafețe.", "Secvență verticală semantică pe mobil, coarse pointer și reduced motion, cu aceeași ordine și același conținut."),
};
